Install script updated, improve conditional force theme instalation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -58,16 +58,25 @@ if [ $? -gt 0 ]; then
 fi
 echo "[done]" ;
 
-# setting vortex-debian as default plymouth theme;
-plymouth-set-default-theme -R vortex-debian
-if [ $? -gt 0 ]; then
-	echo -e "\nan error occoured executing \plymouth-set-default-theme -R vortex-debian\"";
-	exit 1;
-fi
+# Conditional force vortex-debian as default plymouth theme;
+seleccion="";
+while [ true ]; do
+    read -p "Do you like to apply the vortex-debian theme right now?  [Y/n]: " seleccion;
+    if [[ "${seleccion}" = "Y" || "${seleccion}" = "y" || -z $seleccion ]]; then
+		plymouth-set-default-theme -R vortex-debian
+		if [ $? -gt 0 ]; then
+			echo -e "\nan error occoured executing \plymouth-set-default-theme -R vortex-debian\"";
+			exit 1;
+		fi
+        break;
+	elif [[ "${seleccion}" = "N" || "${seleccion}" = "n" ]]; then
+		break;
+    fi
+done
+
+
 echo "[done]";
-
 echo "vortex-debian is your plymouth theme now :)" ;
-
 
 
 exit 0;
